### ISSUE TITLE
Uniform JSON result

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#1]
JSON should have a consistent result format, and base 64 should not be sent back.

on success :

{
 "success" : true,
 "content" : ...
}

on failure :

{
 "success" : false,
 "error" : "Message or Error code"
}

Error codes could be :

1 : Invalid file type
2 : Failure, not a supported screenshot or OCR failed

**Comment by dcmc87** [comment]
Noted. Do you also need me to include a link to the thumbnail?

**Comment by Mokhet** [comment]
Great. No I don't think I need the link to the thumbnail.

**Comment by Mokhet** [comment]
I have tested the new extract, it is **very** nice. I can use it as is, but with little updates it will be just perfect :) Of course only if it doesn't mind you and if it doesn't need you to do too much change.

### For "details" extract:

> {"success": "true", "type": "details", "content": {"energy_def": 5293, "dodge": 14.3, "ignore_dodge": 10.0, "debuff": 4.83, "atkspeed": 109.69, "energy_att": 5729, "phys_att": 12060, "recorate": 212.25, "hp": 24225, "crit_rate": 69.83, "scd": 24.9, "uniform": "", "phys_def": 6239, "tier": 2, "movspeed": 100.0, "id": "warwolf", "defpen": 32.92, "critdamage": 166.86}}

* can you send a boolean to "success" property ?
* can you remove the property "uniform" since it will always be empty (unless MFF UI 3.0 drastically change everything of course) ?
* everything else if perfect

It would look like

>{
>&nbsp;"success": **true**,
>&nbsp;"type": "details",
>&nbsp;"content":
>&nbsp;{
>&nbsp;&nbsp;"energy_def": 5293,
>&nbsp;&nbsp;"dodge": 14.3,
>&nbsp;&nbsp;"ignore_dodge": 10.0,
>&nbsp;&nbsp;"debuff": 4.83,
>&nbsp;&nbsp;"atkspeed": 109.69,
>&nbsp;&nbsp;"energy_att": 5729,
>&nbsp;&nbsp;"phys_att": 12060,
>&nbsp;&nbsp;"recorate": 212.25,
>&nbsp;&nbsp;"hp": 24225,
>&nbsp;&nbsp;"crit_rate": 69.83,
>&nbsp;&nbsp;"scd": 24.9,
>&nbsp;&nbsp;"phys_def": 6239,
>&nbsp;&nbsp;"tier": 2,
>&nbsp;&nbsp;"movspeed": 100.0,
>&nbsp;&nbsp;"id": "warwolf",
>&nbsp;&nbsp;"defpen": 32.92,
>&nbsp;&nbsp;"critdamage": 166.86
>&nbsp;}
>}

### For "gear" extract:

> {"content": {"gear_val": [{"pref": false, "val": 191.5, "type": "hp_by_level"}, {"pref": false, "val": 36.0, "type": "recovery_rate"}, {"pref": false, "val": 211.0, "type": "hp"}, {"pref": false, "val": 103.0, "type": "dodge"}, {"pref": false, "val": 421.0, "type": "hp"}, {"pref": false, "val": 195.0, "type": "recovery_rate"}, {"pref": false, "val": 253.0, "type": "recovery_rate"}, {"pref": false, "val": 334.0, "type": "recovery_rate"}], "char_list": [{"id": "warwolf", "gear_num": 3, "gear_name": "a.o.s bandolier"}]}, "type": "gear", "success": "true"}

* can you send a boolean to "success" property ?
* can you remove the property "pref" since it will always be false ?
* the "gear_name" property will be extracted from my uniforms data, the "gear_num" is enough for me.
* everything else is perfect :D

>{
>&nbsp;"content":
>&nbsp;{
>&nbsp;&nbsp;"gear_val":
>&nbsp;&nbsp;[
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":191.5,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"hp_by_level"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":36.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"recovery_rate"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":211.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"hp"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":103.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"dodge"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":421.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"hp"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":195.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"recovery_rate"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":253.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"recovery_rate"
>&nbsp;&nbsp;&nbsp;},
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"val":334.0,
>&nbsp;&nbsp;&nbsp;&nbsp;"type":"recovery_rate"
>&nbsp;&nbsp;&nbsp;}
>&nbsp;&nbsp;],
>&nbsp;&nbsp;"char_list":
>&nbsp;&nbsp;[
>&nbsp;&nbsp;&nbsp;{
>&nbsp;&nbsp;&nbsp;&nbsp;"id":"warwolf",
>&nbsp;&nbsp;&nbsp;&nbsp;"gear_num":3
>&nbsp;&nbsp;&nbsp;}
>&nbsp;&nbsp;]
>&nbsp;},
>&nbsp;"type":"gear",
>&nbsp;"success":**true**
>}

**Comment by dcmc87** [comment]
Ok sure, that all makes sense. But the uniform in details shouldn't
actually be blank, it's recognising it for all the images I've tried. Could
you post a link to the warwolf image you sent so I can figure out what
happened?

**Comment by Mokhet** [comment]
Wow if you can extract the uniform from the image, this is great and in this case of course please keep it in the response :)

Here is the image :

![detail](https://cloud.githubusercontent.com/assets/24301953/25071846/ae4bbd08-22c1-11e7-9ff0-21fd9490c28b.png)

**Comment by dcmc87** [comment]
Strangely enough it's working for me when I upload that same image, not sure what's happening haha. Did you just try it or was it earlier? Might have changed something on the server in the meantime.

![](https://github.com/dcmc87/ImageHost/blob/master/Screenshot%202017-04-16%2022.34.27.png?raw=true)

**Comment by Mokhet** [comment]
I just tried again twice with the same image, and got the same result. At least it is consistent :D

**Comment by Mokhet** [comment]
Let's keep the "uniform" property in the answer. If it is empty, the user will have to choose instead of confirm it if he wants to use this uniform as the selected one.

**Comment by dcmc87** [comment]
That's really very strange, guess I'll reenable the OCR logging in my next
push so I can hopefully see what happening
