### ISSUE TITLE
Simplified JSON results

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#2]
JSON results should be strictly reduced to required data. With reduced data I will rebuild a compliant format for the web site tool.

If it is a gear extract, JSON content could look like :

[
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 },
 { "type" : "xxx", "val" : 50.0 }
]

If it is a full detail extract, JSON content could be a simple object key/value and would look like :

{
 "name" : "xxx",
 "defense_energy" : 25,
 "defense_physical" : 26,
 "attack_energy" : 27,
 "attack_physical" : 28,
 "hp" : 29
 ...
}

**Comment by dcmc87** [comment]
With regards to the gear extract, do you also want me to send back a list of possible characters? I currently compare the gear name against my database, and usually there is exactly one character associated with that gear name. 

However, there are instances where multiple characters have the same gearname - eg kamala (karachi) and elektra (classic) both have Red Bandana as their 3rd gear

**Comment by Mokhet** [comment]
If you can provide a list of possible characters, it can be nice. But it seems to be a little too much for the purpose of the OCR. I think the link content<>gears<>characters should be performed on the tool using the API instead of the OCR tool itself.

**Comment by dcmc87** [comment]
I'm already generating a character list though, so it would be trivial to include a field :

{
char_list :   {"elektra" : 3, "ms_marvel":3}
gear_values : [{"type" : "xxx".....
}

Alternatively, i can just return the gear name instead and you can match it yourself or do a separate get query call to another endpoint on my API

**Comment by Mokhet** [comment]
Both sound good for me. I think you should go to what is the best for you.
The property/value "char_list" : { "elektra" : 3, "ms_marvel" : 3 } sounds very good for my use. Getting the character id and the gear position is perfect to let me match the characters.
