### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#4]
Since I am using your API, I want to add credits to your work in my tool. Do you have some preferences to the way I show it, the links, the text, the name, etc.

**Comment by dcmc87** [comment]
Haha I don't really have any preferences, just list it any way you want
first and I'll let you know if I would like something edited?

**Comment by Mokhet** [comment]
Arghhhhh that doesn't help me :D

* Should I use the name "dcmc87", "Skyyeblu" or something else ?
* Should I add a link to "https://dancmc.io/mff/ocr", "https://dancmc.io/", the GitHub repository "https://github.com/dcmc87/MFFRosterParserWeb/" or anything else ?
* Do you want a link at all ?

I am thinking about :

> Thanks to Skyyeblu for OCR parsing

With the word "OCR" linking to the GitHub Repository.

What do you think ?

**Comment by dcmc87** [comment]
Yup that sounds good =)

**Comment by Mokhet** [comment]
<img width="245" alt="ocrcredits" src="https://cloud.githubusercontent.com/assets/24301953/25072344/f1160512-22cb-11e7-9c54-5e49860afcaa.png">
