### ISSUE TITLE
Web Service to check server availability

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#5]
Hello,

I do a lot of error check on every calls, but do you think I should first call a service to find out if everything is up an ready on your server ? Or do you think it is useless ?

**Comment by dcmc87** [comment]
If you want, when your page is loading you could post a small blank image
to my api to check for an OK response and display a green light or
something?

**Comment by Mokhet** [comment]
OK, once ready, I will do a XHR call with a white image 1x1 pixels and check for status 200 to enable / disable parsing.

**Comment by Mokhet** [comment]
Right now, localhost checks only, will do live check in a few.

* Check running

<img width="305" alt="ocrcheckonstart" src="https://cloud.githubusercontent.com/assets/24301953/25089447/cc94ef84-237d-11e7-86a9-455c6bffbc55.png">

* Check OK

<img width="225" alt="ocrcheckok" src="https://cloud.githubusercontent.com/assets/24301953/25089453/d2c61afe-237d-11e7-956b-dec3cac55898.png">

* Check KO

<img width="261" alt="ocrcheckfalse" src="https://cloud.githubusercontent.com/assets/24301953/25089460/e0200584-237d-11e7-858d-543036180ebd.png">

* Manual check, limited to 5 attempts. If it failed five times, don't need to keep checking :)

<img width="639" alt="ocrcheckmanual" src="https://cloud.githubusercontent.com/assets/24301953/25089465/ea9c69c6-237d-11e7-8522-7cc76fa10138.png">

**Comment by dcmc87** [comment]
Looks good, btw SSL is now enabled on my site too
