### ISSUE TITLE
Entry limits

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#6]
Should I add some limits to the calls of your service ? For instance, should I limit to X calls by seconds/minutes/days ?

**Comment by dcmc87** [comment]
I'm thinking you probably don't need to, I imagine I can probably handle a
fair number of simultaneous connections, and each image takes only about
half a second to process. With 4 cores I *think* I can handle about 8
images/second, but I don't think we'll know for sure without real life
testing. Just put a beta tag on the page and we'll see how it goes =p

**Comment by Mokhet** [comment]
Good, I add the "beta" tag and we'll see if it is used at all once released :) I don't want to make your server fall down because I have made no specific care of the use.
