### ISSUE TITLE
JSON format gears / char_list

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#7]
Did the property "char_list" changed from

>"char_list" :
>[
> {"id" : "char1", "gear_name" : "xxxx", "gear_num" : 1},
> {"id" : "char2", "gear_name" : "xxxx", "gear_num" : 3}
>]

to

>"char_list" :
>{
> "char1" : 1,
> "char2" : 3 
>}

If yes, nice move. Thanks :D

**Comment by dcmc87** [comment]
Haha actually yes apparently I changed it 3-4 days ago but totally can't
remember doing it. I'll change the readme now. Also note that I added a 4th
error code

**Comment by Mokhet** [comment]
Very good, I was focused on "details" and did not notice the change :)

Good for the new error code, I am adding it right now. I hope I will never get this error from the tool since it would mean I have messed up the checks on my side before calling your API.

**Comment by dcmc87** [comment]
Yeah I actually never get errors 1 and 4 from my website either because the
compression algorithm catches it. But I was also testing a lot using the
Postman program without any client side validation so the codes were useful

**Comment by Mokhet** [comment]
Yes same here, errors 1 and 4 are checked before any call, but it is always good to check everything which might happens. The more errors are checked, the more robust the tools are.
