### ISSUE TITLE
Gears checkbox and import

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#8]
The checkbox is used to indicate if it is a wanted stats or not. If it is checked, the development percent is increased.

Beside the fact I am not sure I want to keep it this way, that is another issue on my repository I should think of later :) How do you think I should handle this flag when importing gear data from screenshot ? So far I can see 4 ways to handle it :

1) Always set to false (unchecked) when imported from screenshot
2) Always set to true (checked) when imported from screenshot
3) Do not change the current state if data already exists
4) Set to false when the type of stat is changed and keep it to true when the type is the same and the flag was checked

Options 1 and 2 are obviously the easiest way to go, but easiest way not always the best way. Which option do you think I should do ?

**Comment by Mokhet** [comment]
I went to option 4. And I think of option 5 : add the checkbox in the import form. We will see later I guess.

**Comment by dcmc87** [comment]
For completely new imports though, would it make more sense to just set it
all to wanted?

**Comment by Mokhet** [comment]
That's right, I did not though of it. I'm doing it right now. Thanks for this suggestion.
